2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Configure stats pid to 20552
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Loading settings from C:\Users\issam\.config\wandb\settings
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Loading settings from C:\Users\issam\OneDrive\Desktop\phd\paper2Implementation\wandb\settings
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'C:\\Users\\issam\\OneDrive\\Desktop\\phd\\paper2Implementation\\main.py', 'program': 'C:\\Users\\issam\\OneDrive\\Desktop\\phd\\paper2Implementation\\main.py'}
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\issam\OneDrive\Desktop\phd\paper2Implementation\wandb\run-20241120_113933-g496kazo\logs\debug.log
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\issam\OneDrive\Desktop\phd\paper2Implementation\wandb\run-20241120_113933-g496kazo\logs\debug-internal.log
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_init.py:init():619] calling init triggers
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {}
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_init.py:init():669] starting backend
2024-11-20 11:39:33,463 INFO    MainThread:20552 [wandb_init.py:init():673] sending inform_init request
2024-11-20 11:39:33,482 INFO    MainThread:20552 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-20 11:39:33,483 INFO    MainThread:20552 [wandb_init.py:init():686] backend started and connected
2024-11-20 11:39:33,498 INFO    MainThread:20552 [wandb_init.py:init():781] updated telemetry
2024-11-20 11:39:33,599 INFO    MainThread:20552 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-20 11:39:35,152 ERROR   MainThread:20552 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity Issam Zarkane not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-11-20 11:39:35,152 ERROR   MainThread:20552 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\issam\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\issam\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity Issam Zarkane not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-11-20 11:39:35,174 WARNING MsgRouterThr:20552 [router.py:message_loop():75] message_loop has been closed
